In [59]:
from df_filter import DF_Filter as f
import pandas as pd

slice = f(pd.read_csv('../../data/data copy/weather_data/cleaned_data/cleaned_chaves_df'))
print(slice.df.columns)
df = slice.filter(2010, 2019, [3, 4, 5])
df.head()

df.to_csv('test_df.csv', index=False)

Index(['dt', 'city_name', 'lat', 'lon', 'temp', 'dew_point', 'feels_like',
       'temp_min', 'temp_max', 'pressure', 'humidity', 'wind_speed',
       'wind_deg', 'clouds_all', 'weather_id', 'weather_main',
       'weather_description'],
      dtype='object')

In [31]:
slice.df.head(5)

,dt,city_name,lat,lon,temp,dew_point,feels_like,temp_min,temp_max,pressure,humidity,wind_speed,wind_deg,clouds_all,weather_id,weather_main,weather_description
0,1979-01-01 00:00:00+00:00,Chaves County,33.475739,-104.47233,-1.17,-3.54,-5.38,-2.19,-0.39,1021,82,3.55,43,92,804,Clouds,overcast clouds
1,1979-01-01 01:00:00+00:00,Chaves County,33.475739,-104.47233,-1.03,-3.69,-5.22,-2.07,-0.21,1022,80,3.57,37,80,803,Clouds,broken clouds
2,1979-01-01 02:00:00+00:00,Chaves County,33.475739,-104.47233,-1.20,-4.16,-5.31,-2.25,-0.34,1023,78,3.42,43,66,803,Clouds,broken clouds
3,1979-01-01 03:00:00+00:00,Chaves County,33.475739,-104.47233,-2.74,-5.22,-6.95,-3.79,-1.88,1024,81,3.17,51,60,803,Clouds,broken clouds
4,1979-01-01 04:00:00+00:00,Chaves County,33.475739,-104.47233,-2.47,-4.96,-6.32,-3.41,-1.72,1024,81,2.85,56,94,804,Clouds,overcast clouds

In [ ]:
import pandas as pd

def filter_and_group(df, start_year, end_year, months):
    """
    Filter and group a DataFrame based on specified year range and months.

    Parameters:
    - df: Pandas DataFrame with a datetime column named 'date'.
    - start_year: int, the starting year for the filter.
    - end_year: int, the ending year for the filter.
    - months: list of int, months to include in the filter (1=Jan, 2=Feb, ..., 12=Dec).

    Returns:
    - A new DataFrame filtered by the specified years and months, grouped by each period.
    """

    # Ensure the 'date' column is a datetime type
    if not pd.api.types.is_datetime64_any_dtype(df['date']):
        df['date'] = pd.to_datetime(df['date'])

    # Filter by year and month
    mask = (df['date'].dt.year >= start_year) & (df['date'].dt.year <= end_year) & (df['date'].dt.month.isin(months))
    filtered_df = df.loc[mask]

    # Group by year and month, assuming we just need to see grouped data
    # If you need to perform any aggregation, you can modify this part
    grouped_df = filtered_df.groupby([filtered_df['date'].dt.year, filtered_df['date'].dt.month])

    # If you want to do operations within groups or visualize them separately:
    # for (year, month), group in grouped_df:
    #     print(f"Data for {year}-{month}:")
    #     print(group)

    return grouped_df

# Example usage:
# Assuming 'data' is your DataFrame and it contains a 'date' column with dates ranging from 1970 to 2000
# data = pd.DataFrame(...)
# result = filter_and_group(data, 1995, 1999, [1, 2, 3, 4])
# Now 'result' holds the grouped data